### ISSUE TITLE
Go Live Checklist

### ISSUE THREAD

**Issue by jonnii** [jbrukh/octopus#76]
- [x] SSL certificate
- [x] AWS credentials and separate buckets for prod/staging
- [ ] New Relic in all environments
- [ ] Production database plan (?)
- [x] Add pingdom checks to avoid heroku sleeping our app
- [ ] Octopus logo
- [x] Google Analytics. 
- [x] MixPanel 
- [x] Sidekiq access only to admins

Add anything else we're missing.
